scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']

  - job_name: 'goapp1'
    scrape_interval: 10s
    static_configs:
      - targets: ['goapp1:8080']
